version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: fastapi_submit_service
    expose:
      - "8000"
    volumes:
      - ./src:/app/src
      - ./output.txt:/app/output.txt
    restart: unless-stopped
    networks:
      - app-network

  envoy:
    image: envoyproxy/envoy:v1.28-latest
    container_name: envoy_proxy
    user: root
    ports:
      - "8080:8080"  # Main traffic port
      - "9901:9901"  # Admin interface
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml
      - ./logs:/var/log/envoy
    command: ["-c", "/etc/envoy/envoy.yaml", "-l", "info"]
    depends_on:
      - fastapi-app
    restart: unless-stopped
    networks:
      - app-network
  stroom-log-sender:
    image: gchq/stroom-log-sender:v2.2.0
    container_name: stroom-log-sender
    volumes:
      - ./logs:/logs
      - ./stroom/stroom-log-sender.yml:/stroom-log-sender/config.yml:ro
      - ./stroom/crontab.txt:/stroom-log-sender/config/crontab.txt:ro
      - ./stroom-sender-logs:/stroom-log-sender/logs  # Add this line
    environment:
      - STROOM_URL=http://log-consumer:8090/stroom/datafeed
      - FEED_NAME=hcm-feed
      - LOG_DIR=/logs
    restart: unless-stopped
    depends_on:
      - envoy
    networks:
      - app-network
  log-consumer:
    build: ./log-consumer
    container_name: log-consumer
    volumes:
      - ./received_logs:/app/received_logs  # Persist received logs
    ports:
      - "8090:8090"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
